### ISSUE TITLE
路径不存在时，最好能够打印错误出来

### ISSUE THREAD

**Issue by maimake** [jessejyang/import-weapp-component#1]
谢谢你提供这么棒的库。

在我使用这库的时候，有一个地方还请能改进下。
extractComponent时，如果引用的组件路径不存在的时候，最好能打印下错误路径出来。

**Comment by jessejyang** [comment]
谢谢反馈，我晚上处理下

**Comment by maimake** [comment]
@JJJYY 另外，我想请教下，我看无论iview-weapp还是zanui-weapp，dist目录下的js等文件都是没有minify的，如果仅仅copy过去的话，略显有些大。不知道兄弟是否有方案？

**Comment by jessejyang** [comment]
![image](https://user-images.githubusercontent.com/32628989/42358292-74dbc7b4-810e-11e8-9bd6-a0bdc9f68fcd.png)
开发工具有这个选项啊

**Comment by jessejyang** [comment]
@maimake ,`v4.5.5`增加了路径错误的抛出

**Comment by maimake** [comment]
@JJJYY 亲测可用，感激万分
