### ISSUE TITLE
vant-weapp中不直接使用但是被组件依赖的模块该如何处理？

### ISSUE THREAD

**Issue by mealayaria** [jessejyang/import-weapp-component#5]
在vant-weapp中有一个common模块，这个并不是被直接使用的组件，却被部分组件依赖，请问类似这样的情况有没有好的方法来处理呢？

**Comment by jessejyang** [comment]
如果是组件内部引用是可以直接 copy 过去的，麻烦告诉我那个组件，我去看下

**Comment by mealayaria** [comment]
![image](https://user-images.githubusercontent.com/4319965/45901227-cc3d6880-be14-11e8-973f-faf02d3319f6.png)

我看了一下，common里是一些公共的工具方法，尤其是create.js，这个文件我大概搜了一下，被应该是所有组件都引用了，对于vant-weapp和之前的zanui-weapp来说，common应该算是个特例，必须要copy的，iview-weapp我发现也有叫base的模块，或许可以做个筛选，对于名字是common或者base之类的直接copy。

**Comment by HuChundong** [comment]
可以直接人工新建一个copy plugin，吧基础模块手动拷贝

**Comment by mealayaria** [comment]
我发现vant-weapp中create.js还引用了mixins模块，这样的话只做common或者base筛选就不行了，或许应该像楼上说的那样新建一个copy plugin，不过我对前端不是很了解，如果能提供一个自定义的选项，只用填路径就更好了

**Comment by jessejyang** [comment]
暂时只能手动 copy 下，或许可以通过编译成 AST 来获取依赖路径的方式解决；如果自定义的话感觉手动配置太麻烦了

**Comment by jessejyang** [comment]
v4.7.3版本已支持读取原生组件的依赖项并拷贝
